#!/bin/bash
# synaptiq-dashboard-with-user-l — Deployment Script
# Generated by Aether Infra Agent on 2026-06-09T16:30:51.433Z
# Usage: ./deploy.sh [--env production|staging]

set -euo pipefail

ENV=${1:-production}
echo "🚀 Deploying synaptiq-dashboard-with-user-l to ${ENV}..."

# Pull latest images
docker-compose pull --quiet 2>/dev/null || true

# Build with cache
echo "📦 Building containers..."
docker-compose build --parallel

# Zero-downtime rolling update
echo "🔄 Rolling update..."
docker-compose up -d --remove-orphans --wait

# Verify health
echo "🏥 Verifying health..."
sleep 5
if docker-compose ps | grep -q "unhealthy"; then
  echo "❌ Health check failed — rolling back"
  docker-compose rollback 2>/dev/null || docker-compose down && exit 1
fi

echo "✅ synaptiq-dashboard-with-user-l deployed successfully"
docker-compose ps
