'use strict';
// Firewall Log Monitor — Defensive Wing
// Generated by Aether on 2026-06-09T16:07:34.267Z

const fs = require('fs');
const EventEmitter = require('events');

class FirewallMonitor extends EventEmitter {
  constructor(logPath = '/var/log/firewall.log') {
    super();
    this.logPath = logPath;
    this.rules = [];
    this.stats = { allowed: 0, blocked: 0, suspicious: 0 };
    this._buffer = '';
  }

  addRule(rule) {
    this.rules.push(rule);
    return this;
  }

  processLine(line) {
    const parsed = this._parseLine(line);
    if (!parsed) return null;

    let action = 'allowed';

    for (const rule of this.rules) {
      if (rule.match(parsed)) {
        action = rule.action;
        break;
      }
    }

    this.stats[action]++;
    const event = { ...parsed, action, timestamp: new Date().toISOString() };
    this.emit('log', event);

    if (action === 'blocked' || action === 'suspicious') {
      this.emit('alert', event);
    }

    return event;
  }

  _parseLine(line) {
    // Parse standard syslog firewall format
    const match = line.match(
      /(w+s+d+s+[d:]+).*?SRC=([d.]+).*?DST=([d.]+).*?PROTO=(w+).*?DPT=(d+)/
    );
    if (!match) return null;
    return { time: match[1], src: match[2], dst: match[3], proto: match[4], dport: parseInt(match[5]) };
  }

  getStats() {
    return { ...this.stats, rules: this.rules.length, logPath: this.logPath };
  }

  // Simulate processing a batch of log entries
  simulate(count = 10) {
    const protos = ['TCP', 'UDP', 'ICMP'];
    const results = [];
    for (let i = 0; i < count; i++) {
      const src = `192.168.${Math.floor(Math.random() * 255)}.${Math.floor(Math.random() * 255)}`;
      const dport = [22, 80, 443, 8080, 3306, 1337][Math.floor(Math.random() * 6)];
      const proto = protos[Math.floor(Math.random() * protos.length)];
      const line = `Jan 01 00:00:00 fw kernel: [FIREWALL] SRC=${src} DST=10.0.0.1 PROTO=${proto} DPT=${dport}`;
      results.push(this.processLine(line));
    }
    return results.filter(Boolean);
  }
}

module.exports = FirewallMonitor;