'use strict';
// built mitm proxy deployment web app with backend server api — Backend Server
// Generated by Aether on 2026-06-09T16:02:55.609Z

const express = require('express');
const { WebSocketServer } = require('ws');
const http = require('http');

const app = express();
const server = http.createServer(app);
const wss = new WebSocketServer({ server });

app.use(express.json());
app.use(express.static('../frontend'));

// Health check
app.get('/health', (req, res) => res.json({ status: 'ok', ts: Date.now() }));

// API routes
app.get('/api/status', (req, res) => {
  res.json({ running: true, uptime: process.uptime() });
});

// WebSocket broadcast utility
function broadcast(data) {
  const msg = JSON.stringify(data);
  wss.clients.forEach((ws) => {
    if (ws.readyState === 1) ws.send(msg);
  });
}

wss.on('connection', (ws) => {
  console.log('[WS] Client connected');
  ws.send(JSON.stringify({ type: 'init', state: { ready: true } }));

  ws.on('message', (raw) => {
    try {
      const msg = JSON.parse(raw);
      console.log('[WS] Received:', msg);
      // Echo back for now
      ws.send(JSON.stringify({ type: 'ack', msg }));
    } catch (e) {
      console.error('[WS] Parse error:', e);
    }
  });

  ws.on('close', () => console.log('[WS] Client disconnected'));
});

const PORT = process.env.PORT || 3001;
server.listen(PORT, () => console.log(`Server listening on http://localhost:${PORT}`));

module.exports = { app, broadcast };