// built mitm proxy deployment web app with backend server api — Frontend App
// Generated by Aether on 2026-06-09T16:01:54.310Z

const ws = new WebSocket(`ws://${location.host}`);
const statusEl = document.getElementById('status');
const dashboard = document.getElementById('dashboard');

ws.onopen = () => {
  statusEl.textContent = 'Connected';
  statusEl.style.color = 'var(--success)';
  console.log('[App] WebSocket connected');
};

ws.onmessage = (ev) => {
  try {
    const data = JSON.parse(ev.data);
    handleMessage(data);
  } catch (e) {
    console.error('[App] Failed to parse message', e);
  }
};

ws.onclose = () => {
  statusEl.textContent = 'Disconnected';
  statusEl.style.color = 'var(--danger)';
};

function handleMessage(data) {
  switch (data.type) {
    case 'init':
      renderDashboard(data.state);
      break;
    case 'update':
      updateWidget(data.id, data.payload);
      break;
    default:
      console.log('[App] Unknown message type:', data.type);
  }
}

function renderDashboard(state) {
  dashboard.innerHTML = '<p>Dashboard loaded. State: ' + JSON.stringify(state) + '</p>';
}

function updateWidget(id, payload) {
  const el = document.getElementById(id);
  if (el) el.innerHTML = JSON.stringify(payload, null, 2);
}