'use strict';

const BaseAgent = require('./base');
const path = require('path');
const fs = require('fs');

class InfraAgent extends BaseAgent {
  constructor(orchestrator) {
    super('infra', orchestrator);
  }

  async execute(task) {
    const { components, goal, outputDir } = task;
    this.log('Drafting infrastructure configuration...');
    await this.sleep(500);

    const goalSlug = goal.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 30);
    const ts = new Date().toISOString();
    const infraFiles = [];

    // Generate Dockerfile
    this.log('Writing Dockerfile...');
    await this.sleep(300);
    const dockerfile = this._genDockerfile(goalSlug, components, ts);
    const dockerfilePath = path.join(outputDir, goalSlug, 'Dockerfile');
    fs.mkdirSync(path.dirname(dockerfilePath), { recursive: true });
    fs.writeFileSync(dockerfilePath, dockerfile, 'utf8');
    infraFiles.push(`${goalSlug}/Dockerfile`);
    this.orchestrator.broadcast({ type: 'file_created', path: `${goalSlug}/Dockerfile`, size: dockerfile.length });

    // Generate docker-compose.yml
    this.log('Writing docker-compose.yml...');
    await this.sleep(250);
    const compose = this._genCompose(goalSlug, components, ts);
    const composePath = path.join(outputDir, goalSlug, 'docker-compose.yml');
    fs.writeFileSync(composePath, compose, 'utf8');
    infraFiles.push(`${goalSlug}/docker-compose.yml`);
    this.orchestrator.broadcast({ type: 'file_created', path: `${goalSlug}/docker-compose.yml`, size: compose.length });

    // Generate deploy script
    this.log('Writing deploy.sh...');
    await this.sleep(200);
    const deployScript = this._genDeploy(goalSlug, ts);
    const deployPath = path.join(outputDir, goalSlug, 'deploy.sh');
    fs.writeFileSync(deployPath, deployScript, 'utf8');
    try { fs.chmodSync(deployPath, 0o755); } catch (err) { console.warn('[infra] chmod failed (non-fatal):', err.message); }
    infraFiles.push(`${goalSlug}/deploy.sh`);
    this.orchestrator.broadcast({ type: 'file_created', path: `${goalSlug}/deploy.sh`, size: deployScript.length });

    // Generate .github/workflows/ci.yml
    this.log('Writing GitHub Actions CI workflow...');
    await this.sleep(300);
    const workflow = this._genWorkflow(goalSlug, ts);
    const workflowPath = path.join(outputDir, goalSlug, '.github/workflows/ci.yml');
    fs.mkdirSync(path.dirname(workflowPath), { recursive: true });
    fs.writeFileSync(workflowPath, workflow, 'utf8');
    infraFiles.push(`${goalSlug}/.github/workflows/ci.yml`);
    this.orchestrator.broadcast({ type: 'file_created', path: `${goalSlug}/.github/workflows/ci.yml`, size: workflow.length });

    this.log(`✓ Infrastructure ready: ${infraFiles.length} config file(s) written`);
    return { files: infraFiles };
  }

  _genDockerfile(slug, components, ts) {
    const hasNode = true;
    const hasPython = components.some((c) => c.name.includes('ml') || c.name.includes('python'));

    return `# ${slug} — Dockerfile
# Generated by Aether Infra Agent on ${ts}

FROM node:20-alpine AS base
WORKDIR /app
RUN apk add --no-cache dumb-init curl

FROM base AS deps
COPY backend/package*.json ./
RUN npm ci --only=production --prefer-offline

FROM base AS runtime
ENV NODE_ENV=production \\
    PORT=3001

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \\
  CMD curl -sf http://localhost:3001/health || exit 1

EXPOSE 3001
USER node
ENTRYPOINT ["dumb-init", "--"]
CMD ["node", "backend/server.js"]
`;
  }

  _genCompose(slug, components, ts) {
    const serviceName = slug.replace(/-/g, '_');
    return `# ${slug} — Docker Compose
# Generated by Aether Infra Agent on ${ts}

version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${slug}:latest
    container_name: ${serviceName}_app
    ports:
      - "\${PORT:-3001}:3001"
    environment:
      - NODE_ENV=\${NODE_ENV:-production}
      - PORT=3001
    restart: unless-stopped
    networks:
      - ${serviceName}_net
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Uncomment for PostgreSQL support
  # db:
  #   image: postgres:16-alpine
  #   container_name: ${serviceName}_db
  #   environment:
  #     POSTGRES_DB: ${serviceName}
  #     POSTGRES_USER: \${DB_USER:-admin}
  #     POSTGRES_PASSWORD: \${DB_PASSWORD:-changeme}
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   networks:
  #     - ${serviceName}_net

networks:
  ${serviceName}_net:
    driver: bridge

# volumes:
#   db_data:
`;
  }

  _genDeploy(slug, ts) {
    return `#!/bin/bash
# ${slug} — Deployment Script
# Generated by Aether Infra Agent on ${ts}
# Usage: ./deploy.sh [--env production|staging]

set -euo pipefail

ENV=\${1:-production}
echo "🚀 Deploying ${slug} to \${ENV}..."

# Pull latest images
docker-compose pull --quiet 2>/dev/null || true

# Build with cache
echo "📦 Building containers..."
docker-compose build --parallel

# Zero-downtime rolling update
echo "🔄 Rolling update..."
docker-compose up -d --remove-orphans --wait

# Verify health
echo "🏥 Verifying health..."
sleep 5
if docker-compose ps | grep -q "unhealthy"; then
  echo "❌ Health check failed — rolling back"
  docker-compose rollback 2>/dev/null || docker-compose down && exit 1
fi

echo "✅ ${slug} deployed successfully"
docker-compose ps
`;
  }

  _genWorkflow(slug, ts) {
    return `# ${slug} — GitHub Actions CI/CD
# Generated by Aether Infra Agent on ${ts}

name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - run: cd backend && npm ci
      - run: cd backend && npm test --if-present

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t ${slug}:\${{ github.sha }} .
      - name: Tag as latest
        run: docker tag ${slug}:\${{ github.sha }} ${slug}:latest
`;
  }
}

module.exports = InfraAgent;